import type { MetadataRoute } from "next";

/**
 * Web App Manifest — served by Next at `/manifest.webmanifest`.
 *
 * Makes NAUB Home Finder installable (Android, Windows, macOS, ChromeOS, iOS via
 * "Add to Home Screen"). Theme + background use the brand red (#FF5A5F). Icons
 * are generated by `pnpm run pwa:icons` (see scripts/generate-pwa-icons.ts) and
 * committed under /public/icons.
 *
 * Verify locally: visit http://localhost:3000/manifest.webmanifest
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "NAUB Home Finder",
    short_name: "NAUB Homes",
    description:
      "NAUB Home Finder — verified student housing near campus with escrow-protected rent payments and trusted landlords.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#FFFFFF",
    theme_color: "#FF5A5F",
    categories: ["house", "real-estate", "education", "lifestyle"],
    lang: "en",
    dir: "ltr",
    icons: [
      { src: "/icons/icon-72x72.png", sizes: "72x72", type: "image/png", purpose: "any" },
      { src: "/icons/icon-96x96.png", sizes: "96x96", type: "image/png", purpose: "any" },
      { src: "/icons/icon-128x128.png", sizes: "128x128", type: "image/png", purpose: "any" },
      { src: "/icons/icon-144x144.png", sizes: "144x144", type: "image/png", purpose: "any" },
      { src: "/icons/icon-152x152.png", sizes: "152x152", type: "image/png", purpose: "any" },
      { src: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-384x384.png", sizes: "384x384", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512x512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Dedicated maskable icon: full-bleed background + house well inside the
      // 80% safe zone so Android adaptive icons never clip the mark.
      { src: "/icons/maskable-512x512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    shortcuts: [
      {
        name: "Browse listings",
        short_name: "Browse",
        description: "Search available housing near campus",
        url: "/properties",
        icons: [{ src: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "My bookings",
        short_name: "Bookings",
        description: "View your bookings and escrow status",
        url: "/bookings",
        icons: [{ src: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Sign in",
        short_name: "Sign in",
        url: "/login",
        icons: [{ src: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}
